process:
  function: ../../actions/example-2/action/index.js
  web: "yes"
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug

    # Adobe Commerce API credentials
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    COMMERCE_STORE_CODES: $COMMERCE_STORE_CODES
    COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
    COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
    COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
    COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET

    # Adobe IMS API credentials
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
    OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
    OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
    OAUTH_ORG_ID: $OAUTH_ORG_ID
    OAUTH_SCOPES: $OAUTH_SCOPES
    OAUTH_HOST: $OAUTH_HOST

  annotations:
    require-adobe-auth: true
    final: true
